### ISSUE TITLE
Sourced functions/varialbes do not appear in autocomplete and are marked as possibly undeclared

### ISSUE THREAD

**Issue by StefanHaunsberger** [JuliaEditorSupport/julia-vscode#229]
When sourcing the function

```julia
function funcTion(x::Int, y::Int)
    return x + y
end
```
either via `include(sourceFile)` or executing the code directly I am experiencing the following two issues in the source editor:

1. The function is not listed in the auto complete box
![image](https://user-images.githubusercontent.com/5872625/28866693-a01ab71c-776b-11e7-8d4b-e1dd3fa24026.png)

2. The function name is underlined green with the hover message "[CSTParser.Diagnostics.Diagnostic] Possible use of undeclared variable funcTion", as shown in the image below.
![image](https://user-images.githubusercontent.com/5872625/28866773-df2de99c-776b-11e7-9568-6e9c09bca3bd.png)

Same is also true for variables.

Session info:
Linux Mint 18 (`uname -r`    4.4.0-78-generic)
VSCode: Version 1.14.2
Julia version 0.6.0
Julia-plugin: 0.6.2

**Comment by ZacLN** [comment]
afaict this is fixed on [v0.7.0-beta.2](https://github.com/JuliaEditorSupport/julia-vscode/releases/tag/v0.7.0-beta.2), if possible could you check?

**Comment by StefanHaunsberger** [comment]
I just downloaded the `language-julia-0.7.0-beta.2.vsix` file, installed and loaded it.
After testing I still experience the described behavior.
...and a question in general, but is it normal for the manually installed extensions that the 'Reload' is constantly there even after a complete restart or is this something that's only happening in my installation?

Thanks

**Comment by KristofferC** [comment]
I had that too. I needed to completely wipe the extension from `.vscode`.

**Comment by StefanHaunsberger** [comment]
@KristofferC 
'remove 0.6.2 --> reload --> install new extension' got rid of the 'Reload'
Thanks

@ZacLN 
The sourced function is in the console auto-complete suggestions (as it was also the case in version 0.6.2) but not in the source editor (with the manually installed version `0.7.7-beta.2.vsix`).
![image](https://user-images.githubusercontent.com/5872625/28870355-d3abaed6-7777-11e7-94bc-f8e593cddc05.png)

**Comment by ZacLN** [comment]
![untitled](https://user-images.githubusercontent.com/5861046/28871268-5f5c136c-7773-11e7-9426-0e4446be9a2f.png)

It looks like you're not getting any completions at all (i.e. `functionloc`), does `View: Toggle Output` and selecting Julia Language Server on the rhs drop down menu show anything?

**Comment by StefanHaunsberger** [comment]
@ZacLN 
In your example the function is included in the drop down menu because it was already mentioned in the script somewhere. If you try to get the same auto completion in a different source file, it won't be included in the drop down menu (at least not in my instance).
When I repeat your example in a different source file where I would like to use the sourced function I get the following:
![image](https://user-images.githubusercontent.com/5872625/28871519-ce595abe-777c-11e7-88df-a4067ab576b6.png)

**Comment by KristofferC** [comment]
I don't think information from the repl is passed back to vscode at all or?

**Comment by ZacLN** [comment]
Ah I see, and how are the files related? If it's not a concrete `include` call we can't pick it up (as of yet) i.e. 
```
for f in ("somefile.jl", "anotherfile.jl")
include(f)
end
```
we can't  associate those files togther

**Comment by ZacLN** [comment]
@KristofferC , yep they're completely separate

**Comment by StefanHaunsberger** [comment]
@ZacLN 
The functions/variables sourced by the include you mentioned are not picked up in the file where you actually perform the call...at least that is the issue that I have here.
Thanks

**Comment by ZacLN** [comment]
Ok, can you post the files, or a smaller example that similarly fails to a gist  so I can have a look at whats going on?

**Comment by StefanHaunsberger** [comment]
This is the link to the gist:
[gistExample](https://gist.github.com/StefanHaunsberger/b8b2d448b10fdb94b9c9f8baad832b78)

from @KristofferC 
> I don't think information from the repl is passed back to vscode at all or?

I think so too because for example if a variable is initialized in the REPL it is not visible in the auto completion drop down menu in the source editor (the variable is also marked as 
"[CSTParser.Diagnostics.Diagnostic] Possible use of undeclared variable <variable>" in the editor).

**Comment by ZacLN** [comment]
Ok I think I've sorted this: there was a missing call in the file watcher so newly created files (after the launch of the language server) weren't being parsed and recognized correctly.
https://github.com/JuliaEditorSupport/LanguageServer.jl/pull/153 should fix this

**Comment by davidanthoff** [comment]
I'll close this, given that we have a fix for this.
